### ISSUE TITLE
alu_full_fifo_in_test

### ISSUE THREAD

**Issue by christinap-vtool** [dimitras-vtool/ALU#1]
I'm running a test (test name: alu_full_fifo_in_test) that sends 20 packets to the fifo_in. So the FIFOs will be full. The FIFO OUT will contain the maximum possible results (4) and the FIFO_IN will contain the maximum possible packets that will be sent for calculation when some results are read from the FIFO OUT. Then the test reads the result register. So when the first packet is moved from FIFO OUT, the ALU can accept a new packet from FIFO_IN. I'm expecting to read 8 results (the 4 that were stored in fifo_out and the 4 that were stored in fifo_in and will be moved to fifo_out after reading).  But as you can see from the waves, when reading the result register, the first 4 results are correct, then the fifth result is skipped, the sixth is calculated and the other 2 aren't calculated. Also, after the sixth packet, the empty_out signal is high. 

![Screenshot 2024-10-02 142027](https://github.com/user-attachments/assets/d3c50b9c-303d-465a-b1f6-2f370b11adb8)

path for waves: /space/users/christinap/alu/alu_verif full_read.trn

**Comment by dimitras-vtool** [comment]
I have made a new commit (661ddf8132484b995e2c5815b3b50f2e9572e80a) that solves the issue. The result of the multiplier was ready while FIFO_OUT was full and when it became empty again, the multiplier wasn't alerting that there is an available result (m_valid_res lasted only one cycle). The multiplier was then getting stuck and the result was never saved. Now, the multiplier alerts FIFO_OUT if a result was produced while FIFO_OUT was unavailable. Same changes where made in the adder.
  However, it should be noted that a multiplication can take up to 16 cycles, while an addition lasts about 3. So, some results may be saved out of order. In FIFO_IN the data is saved with the order they were sent in and also read and forwarded to the ALU in the same order. But, in FIFO_OUT they are saved whenever the results are ready (and the fifo is not full). So in this case (seed 1416401956 in test alu_full_fifo_in_test) as soon as the first read happens, FIFO_OUT is not full anymore and the ALU can start computing again. The fifth package is a multiplication, so the multiplier begins. The 6th package is an addition, so the adder begins after that. The adder finishes two cycles later and the result is saved in the first memory slot of FIFO_OUT, even though it was sent after the multiplication package. When the multiplier finishes (and since in the meantime a second read has happened and FIFO_OUT is once again not full) the multiplication result is saved in the second memory slot. 
  That is precisely the purpose of the ID. The results aren't saved in FIFO_OUT in the same order as they were sent, so the ID helps identify which result belong to which set of operands.

**Comment by christinap-vtool** [comment]
The above changes have caused the following problems:
1) If the 5th packet is for addition, at some point the add_start signal stops rising and as a result some additions are not done at all. As shown in the screenshot below, 5 packets come in for addition, but add_start only goes up 3 times. 
If you want to reproduce this error, try the seeds : 1616201831, 2085190439

![Screenshot 2024-10-04 140619](https://github.com/user-attachments/assets/a54008bb-9e1e-4d08-9486-a3e656e35b01)


2) When the 6th packet is for multiplication an operation is not calculated correctly and returns zeros. I think the problem here is in the m_valid_data signal where while it is in state (next_state) 2 it goes up again and goes to 4 (shift).
If you want to reproduce this error, try the seeds : 1304272913, -523143600

![Screenshot 2024-10-04 135249](https://github.com/user-attachments/assets/814b23d8-d36a-4e22-8262-e79ab470a769)

**Comment by dimitras-vtool** [comment]
Commit: 0cebbdea80d96390d36bac584bfa2a8ecc325b65
Changed the way x_ready_data and x_valid_data and r_en_in are produced. 
The initial bug: FIFO_OUT was full and FIFO_IN was full. Once reading from result register begun, the ALU started reading from FIFO_IN, since FIFO_OUT was not full anymore. However, if the first read from FIFO_IN gave an addition and the multiplier was still not occupied, a second read followed. So far this is allowed. That read also gave an addition, but it happened quickly while the a_ready_data was still high (the first operation is about to begin, but not yet), and the design wasn't stopping and waiting for the adder to be free (which is the desired behavior). It kept reading from FIFO_IN. So, now r_en_in can't become high, not until addition/multiplication signals (op_bits of fifo_in_data) are deasserted.
After that change, the first 8 packets were calculated and written correctly in the FIFOs, but once the 8th one was written in FIFO_OUT and a read from the result register was happening, the design recalculated and rewrote in FIFO_OUT the last result. That was because the x_valid_data was not properly deasserted. It was produced by a posedge detector, while now it is the output of a register, with x_ready_data as the reset.
