### ISSUE TITLE
alu_base_test

### ISSUE THREAD

**Issue by christinap-vtool** [dimitras-vtool/ALU#2]
In some cases the multiplication operation does not give the correct result. For example, as shown in the screenshot below, we need to multiply A8*04 with Id=7e. The result of this operation is FC02A0, but ALU gives FC02A2.

![Screenshot 2024-10-09 115820](https://github.com/user-attachments/assets/7144d049-a3e3-4e15-b6bd-d522257f8828)

test name: alu_base_test
seeds : -202101278, 1143113235

**Comment by dimitras-vtool** [comment]
commit : c0e1d3a8cd72af07f91ddb1c7fca89d279fdfdbd
This multiplier bug was due to reg_c not restarting before a new multiplication, keeping its previous value. reg_C doesn't get loaded with new data at the beginning of a new operation like reg_A and reg_B, but during the multiplication when the first addition occurs. Before that reg_c_out must equal zero.
